### ISSUE TITLE
M04-LAB09: App Service Deploy Task not detecting services created with Azure CLI

### ISSUE THREAD

**Issue by davidokeyode** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#282] opened 2022-08-04 07:56 UTC
### What happened?

Exercise : 01
Task: 01
Step: 07

Description of issue:
App Service Deploy Task not detecting services created with Azure CLI. When a resource is created from the portal, it detects it.

Repro steps:
1. Follow lab instructions
2. Exercise 01; Task 01; Step 07 - When you click on the drop down, it does not detect the resource. If the name is types in manually, deployment fails with a "resource not found error"
3. Workaround seems to be to manually create a similar resource type in the portal, then the task starts to detect the resource

### Lab

Lab 09 Control Deployments using Release Gates

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment] 2022-08-04 13:17
Azure DevOps has lot of know problems with azure resources dropdowns... Many times the issue is fixed by typing the resource name (you may need to unlink parameters on the pipeline level)

**Comment by unaihuete93** [comment] 2022-08-04 13:17
lab will be renewed to YAML soon

**Comment by LuizMacedo** [comment] 2022-10-05 21:12
I am closing the issue. As pointed out by @unaihuete93, the lab will be refreshed soon.

**Closed by LuizMacedo** 2022-10-05 21:12 UTC
Labels: bug
