### ISSUE TITLE
LAB07: Provisioning fails if resource group locations are constraint by policy 

### ISSUE THREAD

**Issue by TobiasBreuer** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#267] opened 2022-07-06 11:26 UTC
### Contact Details

breuer@tobreso.com

### What happened?

Exercise : 01
Task: 01
Step: 11

Description of issue: Within my Azure subscriptions I have a policy which limits the locations to be selectable for new resource-groups. Even though I changed the location to be used to "West Europe" during the "Start deployment" task there is an issue saying:

```
There was an error provisioning the resource group 'VstsRG-DevopsStarter-4385'.
Additional details from the underlying API that might be helpful: Resource 'VstsRG-DevopsStarter-4385' was disallowed by policy
```

The 'VstsRG-DevopsStarter-4385' however seems to be an additional resource group being created and not the one that I specified for the web app to be hosted in (I renamed the resource group in the "Additional settings" section).

Actually I don't think that this is a bug in the Lab itself but in my opinion an issue with the DevOps Starter template task itself. One should be able to specify all required resource-groups and locations and it should not just create something under the hood which we cannot control upfront.

Please let me know if you need any further information or if I should post my feedback somewhere else.
Best regards!

### Lab

Lab 07 Implementing GitHub Actions by using DevOps Starter

### Relevant screenshots

![image](https://user-images.githubusercontent.com/17617068/177539246-2e97d76d-d58f-4370-9f40-7fd777508288.png)

![image](https://user-images.githubusercontent.com/17617068/177539712-b88ba86c-bf84-4c15-b87a-325b2e0da9c9.png)

### Do you want to help us? 👏

- [ ] Create a Pull Request by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment] 2022-08-04 13:10
Hi Tobias, which subscription type did you see. My class this week did not have problems with Azure Pass susbcriptions (as they do not have policies in place). 
DevOps starter uses 2 RGs in your case: 
- one for the deployed services (webapps and so on), which the one shown in the "additional settings" screenshot
-  one for the "DevOps Starter" resource, which is a default one chosen by the platform (the one on second screenshot)

**Comment by TobiasBreuer** [comment] 2022-08-05 07:26
Hi @unaihuete93, I'm using a Pay-Per-Use subscription.
In this subscription I created an initiative with some policies. One of those policies is the "Allowed locations for resource groups" which is restricted to
- "westeurope",
- "germany",
- "germanynorth",
- "germanywestcentral"

The template however tries to create the second "DevOps Starter" resource group in the **"centralus"** region automatically with no option to adapt this. And due to this hard coded use of centralus, the provisioning fails in subscription which do not allow creating resource groups in that region.

**Comment by unaihuete93** [comment] 2022-08-05 11:14
I think the tool is quite limited on this aspect.... Some other services like AKS also create their own RG, but at least the give the option to modify it (using cli). I dont see DevOps Starter supporting it, any idea @LuizMacedo @petender ?

**Comment by petender** [comment] 2022-08-07 16:22
Hi Tobias, the issue you have is related to the "VSTS-xyz-123" Resource Group, which holds the Azure DevOps Starter project, is always created in CentralUS, even if your actual Azure Resource (like the WebApp in the lab scenario) is getting deployed in a totally different region. This is by design, and I don't know of any updates in progress to allow you to change the VSTS region. If you can control your Azure Policies, it would require an exception for Central US, maybe adding a filter for VSTS in the RG naming convention. this makes sure no other Resources can get deployed in Central US.

**Comment by LuizMacedo** [comment] 2022-08-24 21:57
Tobias, thank you for creating the issue. For now, I'm closing it since it's not related to the lab specifically. Thank you, Peter and Unai, for your thoughts.

**Closed by LuizMacedo** 2022-08-24 21:57 UTC
Labels: bug
