### ISSUE TITLE
Lab 10a: Controlling Deployments using Release Gates

### ISSUE THREAD

**Issue by raphasi** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#171] opened 2021-11-22 18:09 UTC
### Contact Details

rapha.si@hotmail.com

### What happened?

Exercise : 01
Task: 18

Description of issue:
When running release pipeline, fails at time of Application Insights task

### Lab

Lab 10a Controlling Deployments using Release Gates

### Relevant screenshots

![image](https://user-images.githubusercontent.com/28764980/142913021-3d6df08f-1c69-456e-82c4-d59a31341a1e.png)

### Do you want to help us? 👏

- [X] I agree to follow this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by prpurand** [comment] 2021-11-29 13:24
hi @raphasi As a work around, you may want to suggest Learners to disable Enable continuous monitoring Task. 
![image](https://user-images.githubusercontent.com/69690284/143875833-3cf669fd-9be3-4935-bb5d-645a233a7d1d.png)


The task creates an availability test in the app insight instance which is associated with the web app. This then causes the azure monitor alert to be fired when the app becomes unavailable. This is an issue to Pipeline dev team, as the pipeline task is using outdated version. There has been such instance in the past:https://github.com/Microsoft/azure-pipelines-tasks/issues/8166 but the issue is closed. We will need to open up similar issue or change the steps to manually create a Url ping test to validate health of the app.
@LuizMacedo @unaihuete93 , any suggestions?

**Comment by unaihuete93** [comment] 2021-12-01 08:45
For all the students I had this week it worked (a few of them had to re-run it) 
![image](https://user-images.githubusercontent.com/64772417/144201322-4762ba10-1537-4b9f-bd9b-71c5ea4aa3ea.png)

**Comment by unaihuete93** [comment] 2021-12-01 08:46
Closing the issue for now, let us know if you need more help ;)

**Closed by unaihuete93** 2021-12-01 08:46 UTC
Labels: bug
