### ISSUE TITLE
M06-LAB06b: Instructions do not match and fails on privacy issues in ADO

### ISSUE THREAD

**Issue by AndrewConniff** [MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions#180] opened 2021-12-08 00:23 UTC
### What happened?

Exercise : 01
Task: 01
Step: 06

Description of issue:

Repro steps:
1. Follow the instructions up to here and when it makes you select a pipeline notice it warns you the project is not public
1.
1.

### Lab

Lab 06b Integrating External Source Control with Azure Pipelines

### Relevant screenshots

paste here 😉

### Do you want to help us? 👏

- [ ] Create a Pull Requestt by following this project's [Contribution Guide](https://github.com/MicrosoftLearning/AZ400-DesigningandImplementingMicrosoftDevOpsSolutions/blob/master/.github/CONTRIBUTING.md#how-can-i-collaborate)

**Comment by unaihuete93** [comment] 2021-12-15 13:13
@AndrewConniff  can you give more details? (steps/task, screenshots or so) @prpurand and I are not able to understand what the issue is...
If you found a workaround please provide a PR
Thanks!

**Comment by unaihuete93** [comment] 2022-01-25 16:48
Closing as no answer has been received

**Closed by unaihuete93** 2022-01-25 16:48 UTC
Labels: bug
